name: Sacred Lotus Love
favicon: null
layout_spectrum: 0.27072
typography_spectrum: 0.025092855328693986
title: Sacred Lotus Love - Create moments of presence and connection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9b0916'
    - '#333333'
    - '#e0c895'
    - '#c3932f'
  brandStrength: 0.75
  lightness: 0.6910036597400904
  saturation: 0.6993337385356426
  rhythmicContrast: 0.9686525834258646
purpose: []
