name: Sacred Lotus Love
favicon: null
layout_spectrum: 0.974
typography_spectrum: 0.27172
title: Sacred Lotus Love - Create moments of presence and connection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9da49c'
    - '#040e03'
    - '#415f1b'
    - '#72727a'
  brandStrength: 0.75
  lightness: 0.6910036597400904
  saturation: 0.6993337385356426
  rhythmicContrast: 0.9686525834258646
purpose: []
